V0x19 docsupdate
SciTools/iris-grib pull request #370
Opened 2023-12-14 16:35 UTC by pp-mo

Pulled in the recent docs fix from main.
Update the front-page version number and the release notes page to the v0.19 state -- which was not done at v0.19.0 release.

Intending to tag this as `v0.19.1`, to get a sensible docs-build up (and which will become the 'stable' endpoint).
Will then merge back (though now expecting to generate some conflicts).

2023-12-14 16:49 UTC, pp-mo commented
**NOTE:** 
TBH I'm not sure if it's worth continuing to write manual release notes.
But it seems simpler just to go along with it for now.

2023-12-15 15:44 UTC, pp-mo commented
Hi @lbdreyer any chance you can check this out ?
As stated, I'm trying to update the docs (mostly just release notes) to reflect the v0.19 release, 
and then publish that via RTD :  I reckon just cutting v0.19.1 will be the most honest way.

2024-01-11 15:14 UTC, ESadek-MO requested changes
Couple of small things, but generally looks good, thanks @pp-mo

2024-01-11 15:14 UTC, ESadek-MO commented on docs/conf.py
> +#language = "en"
```suggestion
# language = "en"
```

2024-01-11 15:14 UTC, ESadek-MO commented on docs/conf.py
> +#html_static_path = ['_static']
```suggestion
# html_static_path = ['_static']
```

2024-01-11 15:14 UTC, ESadek-MO commented on .readthedocs.yml
> +conda:
Does this line (`conda:`) do anything?

2024-01-11 15:14 UTC, ESadek-MO commented on .readthedocs.yml
> +conda:
https://docs.readthedocs.io/en/stable/config-file/v2.html#conda is why I'm thinking it might not

2024-01-11 15:54 UTC, pp-mo commented on .readthedocs.yml
> +conda:
```suggestion
```

No I think you're right  + this line is a mistake !

2024-01-11 15:56 UTC, pp-mo commented
Thanks @ESadek-MO 
Now made those changes -- let's see if it passes.

2024-01-11 16:29 UTC, ESadek-MO approved these changes
Thanks @pp-mo, this looks good to me!

2024-01-11 16:30 UTC, merged