Remove obsolete workarounds.
SciTools/iris-grib pull request #410
Opened 2024-04-12 16:09 UTC by pp-mo

Closes #239 

I'm happy that none of these workarounds are now needed, as all fixed in eccodes.  Long ago, I think.
This passes existing tests, but there is no effective testing of the relevant code.
What I have done is a roundtrip test  : that at least **_does_** seem to work :

```
>>> ellipsoid = GeogCS(EARTH_RADIUS)
>>> data = np.arange(12).reshape(3, 4)
>>> cube = Cube(data, "air_pressure_anomaly")
>>> trans_merc = TransverseMercator(
...     49.0, -2.0, -400000.0, 100000.0, 0.9996012717, ellipsoid
... )
>>> coord = DimCoord(
...     np.arange(3),
...     "projection_y_coordinate",
...     units="m",
...     coord_system=trans_merc,
... )
>>> cube.add_dim_coord(coord, 0)
>>> coord = DimCoord(
...     np.arange(4),
...     "projection_x_coordinate",
...     units="m",
...     coord_system=trans_merc,
... )
>>> cube.add_dim_coord(coord, 1)
>>> coord = DimCoord(
...     np.arange(1),
...     "time",
...     units="days since 2000-01-01",
... )
>>> cube.add_aux_coord(coord, ())
>>> 
>>> print("\nInital cube to save:"); print(cube)

Inital cube to save:
air_pressure_anomaly / (unknown)    (projection_y_coordinate: 3; projection_x_coordinate: 4)
    Dimension coordinates:
        projection_y_coordinate                             x                           -
        projection_x_coordinate                             -                           x
    Scalar coordinates:
        time                        2000-01-01 00:00:00
>>> print("\nsaved + reloaded ...\n")

saved + reloaded ...

>>> result = iris.load_cube('temp.grib2')
>>> print(result); print("  ==> re-loaded coord system = ", result.coord_system())
unknown / (unknown)                 (projection_y_coordinate: 3; projection_x_coordinate: 4)
    Dimension coordinates:
        projection_y_coordinate                             x                           -
        projection_x_coordinate                             -                           x
    Scalar coordinates:
        forecast_period             0 hours
        forecast_reference_time     2000-01-01 00:00:00
        time                        2000-01-01 00:00:00
    Attributes:
        GRIB_PARAM                  GRIB2:d255c255n255
  ==> re-loaded coord system =  TransverseMercator(latitude_of_projection_origin=49.0, longitude_of_central_meridian=-2.0, false_easting=-400000.0, false_northing=100000.0, scale_factor_at_central_meridian=0.9996012449264526, ellipsoid=GeogCS(6371229.0))
>>> 
```

2024-04-16 12:42 UTC, stephenworsley requested changes
`_save_rules` also defines `fixup_int32_as_int32` and `fixup_int32_as_uint32`, should these also be removed like`fixup_float32_from_int32`? Their docstring also mentions how they are a workaround, is this for the same issue?

2024-04-18 15:07 UTC, stephenworsley requested changes
Looks good, there's a couple comments which ought to be removed and this should be good to go.

2024-04-18 15:07 UTC, stephenworsley commented on iris_grib/_load_convert.py
>      # Deal with bug in ECMWF GRIB API (present at 1.12.1) where these
This comment can be removed now

2024-04-18 15:07 UTC, stephenworsley commented on iris_grib/_save_rules.py
>      # but it should accept a float, so work around this.
I believe this comment is no longer applicable.

2024-04-18 15:07 UTC, stephenworsley commented on iris_grib/_save_rules.py
>      # GRIBAPI expects unsigned ints in X1, X2, Y1, Y2 but it should accept
This comment can be removed

2024-04-18 16:48 UTC, pp-mo commented
Thanks @stephenworsley good spots !
I think I addressed those 3 now, please take another look.

2024-04-19 10:24 UTC, stephenworsley approved these changes
Looks good.

2024-04-19 12:01 UTC, merged

2024-04-19 12:51 UTC, pp-mo commented
Thanks @stephenworsley  !