Ruff adopt
SciTools/iris-grib pull request #430
Opened 2024-04-17 13:36 UTC by HGWright

Adopting ruff and making the automatic formatting changes that it requests. The rest are added as temporary excludes to be removed later as seperate issues. This means we can also drop black as ruff takes care of that.

Fixes #384

2024-04-17 14:19 UTC, bjlittle requested changes
@HGWright Lookin' good!

Just a few comments to service, then we can bank this 👍

2024-04-17 14:19 UTC, bjlittle commented on .ruff.toml
> +    "FIX002",
@HGWright Move this rule into the `flake8-fixme` section

2024-04-17 14:19 UTC, bjlittle commented on .ruff.toml
> +    "D105",  # Missing docstring in magic method
@HGWright Just shift this rule down so that it's after `"D103"`

2024-04-17 14:19 UTC, bjlittle commented on pyproject.toml
> +    "iris-grib",
@HGWright Should be `iris_grib`

2024-04-17 14:19 UTC, bjlittle commented on pyproject.toml
> +[tool.ruff.format]
@HGWright We could enable formatting of docstrings with configuring the option [docstring-code-format](https://docs.astral.sh/ruff/settings/#format_docstring-code-format).

There may be new fall-out from enabling this.

2024-04-17 14:19 UTC, bjlittle commented on pyproject.toml
> +    # list specific rules to include that is skipped using numpy convention.
@HGWright Perhaps replace with with a blank line separating it from line +141, then replace with:

```
    # pydocstyle (D)
    # https://docs.astral.sh/ruff/rules/multi-line-summary-first-line/
```

2024-04-17 14:19 UTC, bjlittle commented on pyproject.toml
> +known-first-party = ["iris-grib"]
@HGWright This should be `iris_grib` i.e., the importable package name.

2024-04-17 21:20 UTC, bjlittle approved these changes

2024-04-17 21:20 UTC, merged

2024-04-18 10:52 UTC, stephenworsley commented
Looks like this has accidentally undone part of #433. See #435.